# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fe14_support_editor.ui',
# licensing of '.\fe14_support_editor.ui' applies.
#
# Created: Sat Jan  4 12:33:59 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_support_editor(object):
    def setupUi(self, support_editor):
        support_editor.setObjectName("support_editor")
        support_editor.resize(875, 516)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(support_editor)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(support_editor)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.characters_list_view = QtWidgets.QListView(support_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.characters_list_view.sizePolicy().hasHeightForWidth())
        self.characters_list_view.setSizePolicy(sizePolicy)
        self.characters_list_view.setMinimumSize(QtCore.QSize(325, 0))
        self.characters_list_view.setBaseSize(QtCore.QSize(0, 0))
        self.characters_list_view.setObjectName("characters_list_view")
        self.verticalLayout.addWidget(self.characters_list_view)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(support_editor)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(support_editor)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.widget = QtWidgets.QWidget(support_editor)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget)
        self.listWidget_2 = QtWidgets.QListWidget(support_editor)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.widget_2 = QtWidgets.QWidget(support_editor)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.horizontalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(support_editor)
        QtCore.QMetaObject.connectSlotsByName(support_editor)

    def retranslateUi(self, support_editor):
        support_editor.setWindowTitle(QtWidgets.QApplication.translate("support_editor", "Form", None, -1))
        self.lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("support_editor", "Search...", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("support_editor", "Add", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("support_editor", "Remove", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("support_editor", "Type", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("support_editor", "Romantic", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("support_editor", "Platonic", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("support_editor", "Fast Romantic", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("support_editor", "Fast Platonic", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("support_editor", "Tag", None, -1))
        self.lineEdit_2.setInputMask(QtWidgets.QApplication.translate("support_editor", "HH HH HH HH;0", None, -1))

