name: Python package


on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      PYTHONIOENCODING: utf-8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          python scripts/render_templates.py

      - name: Package application (MacOS)
        if: runner.os == 'macOS'
        run: |
          virtualenv venv
          source venv/bin/activate
          maturin develop --release
          pyinstaller -F -n paragon -i paragon.ico paragon/ui/main.py
          rm -rf dist/paragon.app
          cp paragon.ico dist/paragon.ico
          cp -R Data dist/Data
          cp -R resources dist/resources
          cp -R third-party-licenses dist/third-party-licenses
          cp -R LICENSE.txt dist/LICENSE.txt

      - name: Package application (Windows)
        if: runner.os == 'Windows'
        run: |
          virtualenv venv
          .\package.bat
     
      - name: Package application (Linux)
        if: runner.os == 'Linux'
        run: |
          virtualenv venv
          source venv/bin/activate
          maturin develop --release
          pyinstaller -F -n paragon -i paragon.ico paragon/ui/main.py
          cp paragon.ico dist/paragon.ico
          cp -R Data dist/Data
          cp -R resources dist/resources
          cp -R third-party-licenses dist/third-party-licenses
          cp -R LICENSE.txt dist/LICENSE.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Paragon-${{ runner.os }}
          path: dist
